### ISSUE TITLE
posting event ProxyInitializeEvent

### ISSUE THREAD

**Issue by wildmaster84** [bhopahk/LANBroadcaster#3]
while starting up velocity there was an error posting event ProxyInitializeEvent.

Log:

> java.lang.NoClassDefFoundError: net/kyori/text/serializer/ComponentSerializers
        at me.bhop.lanbroadcaster.velocity.LANBroadcasterVelocity.onProxyInit(LANBroadcasterVelocity.java:30) ~[?:?]
        at net.kyori.event.asm.generated.d810a2f6d7.LANBroadcasterVelocity-onProxyInit-ProxyInitializeEvent-2.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.text.serializer.ComponentSerializers
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[proxy.jar:1.0.6-SNAPSHOT (git-5c6163d8-b195)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]

**Comment by SebaSphere** [comment]
Should be fixed as per
https://github.com/bhopahk/LANBroadcaster/pull/5
